package config

import (
	"fmt"

	"github.com/hashicorp/hcl"
)

// Config holds the plugin configuration parsed from SPIRE agent.conf plugin_data block.
//
// Example HCL:
//
//	plugin_data {
//	  hash_manifest_path   = "/etc/spire/jvm-hashes.json"
//	  block_on_attach_socket = true
//	}
type Config struct {
	// HashManifestPath is the path to the JSON file generated by CI/CD
	// that contains expected SHA-256 hashes for each jar file.
	// Required. If empty, Perевірка 3 (jar hash) is skipped.
	HashManifestPath string `hcl:"hash_manifest_path"`

	// BlockOnAttachSocket controls behaviour when the JVM Attach API socket
	// (.java_pid<PID>) is detected.
	//   true  — attestation fails with an error (strict mode)
	//   false — attestation continues but selector jvm:attach_socket_exposed=true is set
	BlockOnAttachSocket bool `hcl:"block_on_attach_socket"`
}

// Parse decodes raw HCL string (the plugin_data block body) into Config.
func Parse(hclData string) (*Config, error) {
	cfg := &Config{}
	if err := hcl.Decode(cfg, hclData); err != nil {
		return nil, fmt.Errorf("failed to parse plugin config: %w", err)
	}
	return cfg, nil
}
