apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: spire
spec:
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8081
  type: ClusterIP