apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
spec:
  template:
    spec:
      initContainers:
        - name: install-jvm-attestor
          $patch: delete
      volumes:
        - name: jvm-plugin
          $patch: delete
        - name: jvm-hashes
          $patch: delete
      containers:
        - name: spire-agent
          # VolumeMount entries merge by mountPath, not name.
          volumeMounts:
            - mountPath: /opt/spire/plugins
              $patch: delete
            - mountPath: /etc/spire/jvm-hashes
              $patch: delete
