package internal

import (
	"encoding/json"
	"fmt"
	"os"
	"sync"
	"time"
)

// hashManifest is the structure of the JSON file generated by the CI/CD pipeline.
// It maps jar paths (as they appear inside the container) to their expected
// SHA-256 hex digests.
//
// Example:
//
//	{
//	  "version": 1,
//	  "generated_at": "2026-05-27T07:00:00Z",
//	  "generated_by": "github-actions/build@sha:abc123",
//	  "jars": {
//	    "/app/payments-service.jar": "a3f2b1c4..."
//	  }
//	}
type hashManifest struct {
	Version     int               `json:"version"`
	GeneratedAt time.Time         `json:"generated_at"`
	GeneratedBy string            `json:"generated_by"`
	Jars        map[string]string `json:"jars"`
}

type ManifestCache struct {
	mu    sync.RWMutex
	mtime int64
	jars  map[string]string
}

func NewManifestCache() *ManifestCache {
	return &ManifestCache{}
}

func (c *ManifestCache) Load(path string) (map[string]string, error) {
	if path == "" {
		return nil, fmt.Errorf("hash_manifest_path is not configured")
	}

	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("cannot stat manifest %s: %w", path, err)
	}
	currentMtime := info.ModTime().Unix()

	c.mu.RLock()
	if c.mtime == currentMtime && c.jars != nil {
		jars := c.jars
		c.mu.RUnlock()
		return jars, nil
	}
	c.mu.RUnlock()

	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read manifest %s: %w", path, err)
	}

	var m hashManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("cannot parse manifest %s: %w", path, err)
	}
	if m.Version != 1 {
		return nil, fmt.Errorf("unsupported manifest version %d (expected 1)", m.Version)
	}
	if len(m.Jars) == 0 {
		return nil, fmt.Errorf("manifest %s contains no jar entries", path)
	}

	c.mu.Lock()
	c.mtime = currentMtime
	c.jars = m.Jars
	c.mu.Unlock()

	return m.Jars, nil
}