apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
  labels:
    app: my-test-app
spec:
  serviceAccountName: test-sa
  containers:
  - name: spire-client
    image: ghcr.io/spiffe/spire-agent:1.11.2
    command: ["/opt/spire/bin/spire-agent", "api", "fetch", "x509", "-socketPath", "/tmp/spire/agent.sock"]
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /tmp/spire
      readOnly: true
  volumes:
  - name: spire-agent-socket
    hostPath:
      path: /run/spire/sockets
      type: DirectoryOrCreate
  restartPolicy: Never